# Generated by Django 3.1.1 on 2020-11-05 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='volume',
            new_name='voltage',
        ),
    ]
